TRAINING_SAMPLES = [
    ("lunch at restaurant", "Food"),
    ("dinner takeaway", "Food"),
    ("grocery shopping", "Food"),
    ("coffee and snacks", "Food"),
    ("uber to office", "Transport"),
    ("bus ticket", "Transport"),
    ("fuel refill", "Transport"),
    ("train pass", "Transport"),
    ("monthly rent", "Housing"),
    ("hotel booking", "Housing"),
    ("apartment maintenance", "Housing"),
    ("electricity bill", "Utilities"),
    ("water bill", "Utilities"),
    ("internet payment", "Utilities"),
    ("online course", "Education"),
    ("text books", "Education"),
    ("tuition payment", "Education"),
    ("doctor appointment", "Healthcare"),
    ("pharmacy medicine", "Healthcare"),
    ("hospital bill", "Healthcare"),
    ("movie tickets", "Entertainment"),
    ("concert booking", "Entertainment"),
    ("streaming subscription", "Entertainment"),
    ("clothes shopping", "Shopping"),
    ("phone accessories", "Shopping"),
    ("supermarket household items", "Shopping"),
    ("miscellaneous payment", "Other"),
    ("office supplies", "Other"),
    ("general expense", "Other"),
]
